name: Next Branch - Push

#on:
#  push:
#    branches: [next]

on:
  pull_request:
    branches: [next, v5]


env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      cypress-folders: ${{ steps.list-cypress-folders.outputs.cypress-folders }}
      jest-packages: ${{ steps.list-jest-packages.outputs.jest-packages }}
      day: ${{ steps.get-day.outputs.day }}
      ts: ${{ steps.get-timestamp.outputs.ts }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - name: Get day of the month
        id: get-day
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=ts::$(node --eval "console.log(new Date().getTime())")"

      - name: List packages with Jest tests
        id: list-jest-packages
        run: echo "::set-output name=jest-packages::$(node scripts/listPackagesWithTests.js)"

      - name: List Cypress tests folders
        id: list-cypress-folders
        run: echo "::set-output name=cypress-folders::$(node scripts/listCypressTestsFolders.js)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        id: cached-packages
        with:
          path: .webiny/cached-packages
          key: ${{ runner.os }}-${{ steps.get-day.outputs.day }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' || steps.cached-packages.outputs.cache-hit != 'true'
        run: yarn --immutable

      - name: Build packages
        if: steps.cached-packages.outputs.cache-hit != 'true'
        run: node scripts/buildWithCache.js

  cypress-tests-admin-area-installation:
    needs: init
    name: Cypress Tests - Admin Area Installation
    runs-on: ubuntu-latest
    environment: next
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ELASTIC_SEARCH_DOMAIN_NAME: ${{ secrets.AWS_ELASTIC_SEARCH_DOMAIN_NAME }}
      ELASTIC_SEARCH_INDEX_PREFIX: ${{ needs.init.outputs.ts }}_
      PULUMI_SECRETS_PROVIDER: ${{ secrets.PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      WEBINY_PULUMI_BACKEND: ${{ secrets.WEBINY_PULUMI_BACKEND }}_${{ needs.init.outputs.ts }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .webiny/cached-packages
          key: ${{ runner.os }}-${{ needs.init.outputs.day }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: node scripts/buildWithCache.js

      - name: Set up Cypress config
        run: yarn setup-cypress

      - name: Cypress - run installation wizard test
        run: yarn cypress run --spec "cypress/integration/adminInstallation/**/*.spec.js"

      - name: Upload screenshots to Slack
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: C027VQG8080
          workdir: cypress
          message-text: Cypress tests failed! Screenshots have been placed in this thread, good luck.

      - name: Trigger cleanup
        if: failure()
        run: npx https://gist.github.com/doitadrian/6a3fa9f6b0e450ab88e3a5ba23f4e789 --event e2e-cleanup --payload "{\"ts\":\"${{ needs.init.outputs.ts }}\",\"workflow\":\"${{ github.workflow }}\",\"commit\":\"${{ github.sha }}\"}"

  cypress-tests-admin-area:
    needs: cypress-tests-admin-area-installation
    name: ${{ matrix.cypress-folder }} (${{ matrix.os }}, Node v${{ matrix.node }})
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]
        cypress-folder: ${{ fromJson(needs.init.outputs.cypress-folders) }}
    runs-on: ubuntu-latest
    environment: next
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ELASTIC_SEARCH_DOMAIN_NAME: ${{ secrets.AWS_ELASTIC_SEARCH_DOMAIN_NAME }}
      ELASTIC_SEARCH_INDEX_PREFIX: ${{ needs.init.outputs.ts }}_
      PULUMI_SECRETS_PROVIDER: ${{ secrets.PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      WEBINY_PULUMI_BACKEND: ${{ secrets.WEBINY_PULUMI_BACKEND }}_${{ needs.init.outputs.ts }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .webiny/cached-packages
          key: ${{ runner.os }}-${{ needs.init.outputs.day }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: webiny-js
        run: yarn --immutable

      - name: Build packages
        working-directory: webiny-js
        run: node scripts/buildWithCache.js

      - name: Set up Cypress config
        run: yarn setup-cypress

      - name: Cypress - run "${{ matrix.cypress-folder }}" tests
        run: yarn cypress run --spec "${{ matrix.cypress-folder }}"

      - name: Upload screenshots to Slack
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: C027VQG8080
          workdir: cypress
          message-text: Cypress tests failed! Screenshots have been placed in this thread, good luck.

      - name: Trigger cleanup
        if: always()
        run: npx https://gist.github.com/doitadrian/6a3fa9f6b0e450ab88e3a5ba23f4e789 --event e2e-cleanup --payload "{\"ts\":\"${{ needs.init.outputs.ts }}\",\"workflow\":\"${{ github.workflow }}\",\"commit\":\"${{ github.sha }}\"}"
