name: Next Branch - Push

#on:
#  push:
#    branches: [next]

on:
  pull_request:
    branches: [next, v5]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  AWS_REGION: eu-central-1

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      jest-packages: ${{ steps.list-jest-packages.outputs.jest-packages }}
      day: ${{ steps.get-day.outputs.day }}
      ts: ${{ steps.get-timestamp.outputs.ts }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - name: Get day of the month
        id: get-day
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=ts::$(node --eval "console.log(new Date().getTime())")"

      - name: List packages with Jest tests
        id: list-jest-packages
        run: echo "::set-output name=jest-packages::$(node scripts/listPackagesWithTests.js)"

      - uses: actions/cache@v2
        id: global-daily-packages-cache
        with:
          path: .webiny/cached-packages
          key: ${{ runner.os }}-${{ steps.get-day.outputs.day }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - uses: actions/cache@v2
        id: cached-packages2
        with:
          path: branch-v5/.webiny/cached-packages
          key: ${{ runner.os }}-${{ steps.get-day.outputs.day }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - uses: actions/cache@v2
        id: cached-packages3
        with:
          path: branch-XYZ/.webiny/cached-packages
          key: ${{ runner.os }}-${{ steps.get-day.outputs.day }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}
