name: Pull Requests

on:
  pull_request:
    branches: [next, v5]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  BUILD_OVERRIDES: '{"tsConfig":{"compilerOptions":{"skipLibCheck":true}}}'

jobs:
  cache-dependencies-packages:
    name: Cache dependencies and packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - name: List dirs
        run: ls -alh

      - name: List dirs
        run: cd packages && ls -alh

      - name: Create project-files artifact
        uses: actions/upload-artifact@v2
        with:
          name: project-files
          retention-days: 1
          path: |
            .
            !node_modules/**/*
            !**/node_modules/**/*
            !.yarn/cache/**/*
