name: v5 Branch - Push

#on:
#  push:
#    branches: [v5]

on:
  pull_request:
    branches: [next, v5]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  AWS_REGION: eu-central-1

jobs:
  e2e-init:
    name: Init (E2E)
    runs-on: ubuntu-latest
    outputs:
      cypress-folders: ${{ steps.list-cypress-folders.outputs.cypress-folders }}
      ts: ${{ steps.get-timestamp.outputs.ts }}
      webiny-version: ${{ steps.get-webiny-version.outputs.webiny-version }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - name: Get current version of Webiny
        id: get-webiny-version
        run: echo "::set-output name=webiny-version::$(node --eval "console.log(require('./lerna.json').version)")"

      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=ts::$(node --eval "console.log(new Date().getTime())")"

      - name: List Cypress tests folders
        id: list-cypress-folders
        run: echo "::set-output name=cypress-folders::$(node scripts/listCypressTestsFolders.js)"

  e2e-project-setup-1:
    needs: e2e-init
    name: Project setup (E2E) 1
    runs-on: ubuntu-latest
    outputs:
      cypress-config: ${{ steps.save-cypress-config.outputs.cypress-config }}
    environment: next
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ELASTIC_SEARCH_DOMAIN_NAME: ${{ secrets.AWS_ELASTIC_SEARCH_DOMAIN_NAME }}
      ELASTIC_SEARCH_INDEX_PREFIX: ${{ needs.e2e-init.outputs.ts }}_
      PULUMI_SECRETS_PROVIDER: ${{ secrets.PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      WEBINY_PULUMI_BACKEND: ${{ secrets.WEBINY_PULUMI_BACKEND }}_${{ needs.e2e-init.outputs.ts }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2
        with:
          #  fetch-depth: 10
          path: branch-v5
          # DELETE - Prevents the detached HEAD problem (https://github.com/actions/checkout/issues/124)
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: branch-v5/.yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('branch-v5/**/yarn.lock') }}

      - uses: actions/cache@v2
        id: cached-packages
        with:
          path: branch-v5/.webiny/cached-packages
          key: ${{ runner.os }}-${{ needs.e2e-init.outputs.webiny-version }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - name: Install dependencies
        working-directory: branch-v5
        run: yarn --immutable

      - name: Build packages
        working-directory: branch-v5
        run: node scripts/buildWithCache.js

      # Publish built packages to Verdaccio.
      - name: Start Verdaccio local server
        working-directory: branch-v5
        run: npx pm2 start verdaccio -- -c .verdaccio.yaml

      - name: Create ".npmrc" file in the project root, with a dummy auth token
        working-directory: branch-v5
        run: echo '//localhost:4873/:_authToken="dummy-auth-token"' > .npmrc

      - name: Configure NPM to use local registry
        run: npm config set registry http://localhost:4873

      - name: Set git email
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username
        run: git config --global user.name "webiny-bot"

      - name: Version packages (no push, no changelog)
        working-directory: branch-v5
        run: yarn lerna:version:verdaccio

      - name: Release to Verdaccio
        working-directory: branch-v5
        run: yarn lerna:publish:verdaccio

      - name: Create verdaccio-files artifact
        uses: actions/upload-artifact@v2
        with:
          name: verdaccio-files
          retention-days: 1
          path: |
            branch-v5/.verdaccio/
            branch-v5/.verdaccio.yaml

        # Create a new Webiny project, deploy it, and complete the installation wizard.
      - name: Disable Webiny telemetry
        run: >
          mkdir ~/.webiny &&
          echo '{ "id": "ci", "telemetry": false }' > ~/.webiny/config

      - name: Create directory
        run: mkdir xyz

      - name: Create a new Webiny project
        working-directory: xyz
        run: >
          npx create-webiny-project@next test-project
          --tag next --no-interactive
          --assign-to-yarnrc '{"npmRegistryServer":"http://localhost:4873","unsafeHttpWhitelist":["localhost"]}'
          --template-options '{"region":"${{ env.AWS_REGION }}","storageOperations":"ddb-es"}'

      - name: Print CLI version
        working-directory: xyz/test-project
        run: yarn webiny --version

  e2e-project-setup-2:
    needs: e2e-init
    name: Project setup (E2E) 2
    runs-on: ubuntu-latest
    outputs:
      cypress-config: ${{ steps.save-cypress-config.outputs.cypress-config }}
    environment: next
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ELASTIC_SEARCH_DOMAIN_NAME: ${{ secrets.AWS_ELASTIC_SEARCH_DOMAIN_NAME }}
      ELASTIC_SEARCH_INDEX_PREFIX: ${{ needs.e2e-init.outputs.ts }}_
      PULUMI_SECRETS_PROVIDER: ${{ secrets.PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      WEBINY_PULUMI_BACKEND: ${{ secrets.WEBINY_PULUMI_BACKEND }}_${{ needs.e2e-init.outputs.ts }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2
        with:
          #  fetch-depth: 10
          path: branch-v5
          # DELETE - Prevents the detached HEAD problem (https://github.com/actions/checkout/issues/124)
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: branch-v5/.yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('branch-v5/**/yarn.lock') }}

      - uses: actions/cache@v2
        id: cached-packages
        with:
          path: branch-v5/.webiny/cached-packages
          key: ${{ runner.os }}-${{ needs.e2e-init.outputs.webiny-version }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - name: Install dependencies
        working-directory: branch-v5
        run: yarn --immutable

      - name: Build packages
        working-directory: branch-v5
        run: node scripts/buildWithCache.js

      # Publish built packages to Verdaccio.
      - name: Start Verdaccio local server
        working-directory: branch-v5
        run: npx pm2 start verdaccio -- -c .verdaccio.yaml

      - name: Create ".npmrc" file in the project root, with a dummy auth token
        working-directory: branch-v5
        run: echo '//localhost:4873/:_authToken="dummy-auth-token"' > .npmrc

      - name: Configure NPM to use local registry
        run: npm config set registry http://localhost:4873

      - name: Set git email
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username
        run: git config --global user.name "webiny-bot"

      - name: Version packages (no push, no changelog)
        working-directory: branch-v5
        run: yarn lerna:version:verdaccio

      - name: Release to Verdaccio
        working-directory: branch-v5
        run: yarn lerna:publish:verdaccio

      - name: Create verdaccio-files artifact
        uses: actions/upload-artifact@v2
        with:
          name: verdaccio-files
          retention-days: 1
          path: |
            branch-v5/.verdaccio/
            branch-v5/.verdaccio.yaml

        # Create a new Webiny project, deploy it, and complete the installation wizard.
      - name: Disable Webiny telemetry
        run: >
          mkdir ~/.webiny &&
          echo '{ "id": "ci", "telemetry": false }' > ~/.webiny/config

      - name: Create project directory (with Yarn cache folder)
        run: mkdir -p xyz/test-project/.yarn/cache

      - name: Copy cache files from webiny-js repository
        run: cp -rf branch-v5/.yarn/cache xyz/test-project/.yarn

      - name: Copy cache files from webiny-js repository 1
        run: ls -alh xyz/test-project

      - name: Copy cache files from webiny-js repository 2
        run: ls -alh xyz/test-project/.yarn

      - name: Copy cache files from webiny-js repository 3
        run: ls -alh xyz/test-project/.yarn/cache

      - name: Create a new Webiny project
        working-directory: xyz
        run: >
          npx create-webiny-project@next test-project
          --force --tag next --no-interactive
          --assign-to-yarnrc '{"npmRegistryServer":"http://localhost:4873","unsafeHttpWhitelist":["localhost"]}'
          --template-options '{"region":"${{ env.AWS_REGION }}","storageOperations":"ddb-es"}'

      - name: Print CLI version
        working-directory: xyz/test-project
        run: yarn webiny --version

      - name: Copy cache files from webiny-js repository 1
        run: ls -alh xyz/test-project

      - name: Copy cache files from webiny-js repository 2
        run: ls -alh xyz/test-project/.yarn

      - name: Copy cache files from webiny-js repository 3
        run: ls -alh xyz/test-project/.yarn/cache
