name: v5 Branch - Push

#on:
#  push:
#    branches: [v5]

on:
  pull_request:
    branches: [next, v5]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  AWS_REGION: eu-central-1

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      str: ${{ steps.str.outputs.webiny-version }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: get
        id: get
        run: echo "This is a string."

      - name: str
        id: str
        run: echo "::set-output name=str::${{ steps.get }}"

