name: v5 Branch - Push

#on:
#  push:
#    branches: [v5]

on:
  pull_request:
    branches: [next, v5]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  AWS_REGION: eu-central-1

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    outputs:
      cypress-folders: ${{ steps.list-cypress-folders.outputs.cypress-folders }}
      ts: ${{ steps.get-timestamp.outputs.ts }}
      webiny-version: ${{ steps.get-webiny-version.outputs.webiny-version }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#          path: webiny-js

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: webiny-js
          # Prevents the detached HEAD problem (https://github.com/actions/checkout/issues/124)
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get current version of Webiny
        working-directory: webiny-js
        id: get-webiny-version
        run: echo "::set-output name=webiny-version::$(node --eval "console.log(require('./lerna.json').version)")"

      - name: Get timestamp
        working-directory: webiny-js
        id: get-timestamp
        run: echo "::set-output name=ts::$(node --eval "console.log(new Date().getTime())")"

      - name: List packages with Jest tests
        working-directory: webiny-js
        id: list-jest-packages
        run: echo "::set-output name=jest-packages::$(node scripts/listPackagesWithTests.js)"

      - name: List Cypress tests folders
        working-directory: webiny-js
        id: list-cypress-folders
        run: echo "::set-output name=cypress-folders::$(node scripts/listCypressTestsFolders.js)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('webiny-js/**/yarn.lock') }}

      - uses: actions/cache@v2
        id: cached-packages
        with:
          path: webiny-js/.webiny/cached-packages
          key: ${{ runner.os }}-${{ steps.get-webiny-version.outputs.webiny-version }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - name: Install dependencies
        working-directory: webiny-js
        if: steps.yarn-cache.outputs.cache-hit != 'true' || steps.cached-packages.outputs.cache-hit != 'true'
        run: yarn --immutable

      - name: Build packages
        working-directory: webiny-js
        if: steps.cached-packages.outputs.cache-hit != 'true'
        run: node scripts/buildWithCache.js

      - name: Start Verdaccio local server
        working-directory: webiny-js
        run: npx pm2 start verdaccio -- -c .verdaccio.yaml

      - name: Create ".npmrc" file in the project root, with a dummy auth token
        working-directory: webiny-js
        run: echo '//localhost:4873/:_authToken="dummy-auth-token"' > .npmrc

      - name: Configure NPM to use local registry
        working-directory: webiny-js
        run: npm config set registry http://localhost:4873

      - name: Set git email
        working-directory: webiny-js
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username
        working-directory: webiny-js
        run: git config --global user.name "webiny-bot"

      - name: Version packages (no push, no changelog)
        working-directory: webiny-js

        run: yarn lerna:version:verdaccio
      - name: Release to Verdaccio
        working-directory: webiny-js
        run: yarn lerna:publish:verdaccio

      - name: Create verdaccio-files artifact
        uses: actions/upload-artifact@v2
        with:
          name: verdaccio-files
          retention-days: 1
          path: |
            webiny-js/.verdaccio/
            webiny-js/.verdaccio.yaml

